print("================================")
print("       ATM10 DEVKIT")
print("================================")
print()
print("Instalador funcionando!")
print()
print("Computer ID: " .. os.getComputerID())
print("Label: " .. (os.getComputerLabel() or "sem nome"))
print()
print("Instalacao concluida!")
